title: IT-блог
description: > # this means to ignore newlines until "baseurl:"
  Blog with theme Future Imperfect<br>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://https://ghdehddnr92.github.io/" # the base hostname & protocol for your site, e.g. http://example.com


author:
  name: 'DoooongWoooook'
  last_name: 'Hoooong'
  cv: '//kaptn.ru'
  avatar: '/images/avatar.jpeg'
  github_username:  ghdehddnr92
  email: ghdehddnr92@gmail.com
  vk_id: id201664979
  telegram_name: 동욱 
  logo: '/images/logo.svg'

# Build settings
markdown: kramdown

permalink: /:categories/:year/:title.html


